apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: alpine-deployment
  labels:
    run: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      run: alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: alpine
    spec:
      containers:
      - image: alpine:latest
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
        name: alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: alpine-service
  namespace: alpine-deployment
spec:
  selector:
    run: alpine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP