apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    stream {
        upstream mongodb_backend {
            server mongo-service:27017;
        }

        server {
            listen 27017;
            proxy_pass mongodb_backend;
        }
    }